name: intro_slider_example
description: Demonstrates how to use the intro_slider plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intro_slider:
    path: ../

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

flutter:

  uses-material-design: true

  assets:
    - images/photo_eraser.png
    - images/photo_pencil.png
    - images/photo_ruler.png
    - images/photo_school.png
    - images/photo_museum.png
    - images/photo_coffee_shop.png
    - images/result.svg


  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf